//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineReservationGUI.Intel_AirlineReservationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookingHistory", Namespace="http://schemas.datacontract.org/2004/07/Intel_AirlineReservationService.Serializa" +
        "ble_Models")]
    [System.SerializableAttribute()]
    public partial class BookingHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime arrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string arrivalLocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan arrivalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime bookingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime departureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureLocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan departureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string flightNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double flightPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameOnTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int seatIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime arrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                if ((this.arrivalDateField.Equals(value) != true)) {
                    this.arrivalDateField = value;
                    this.RaisePropertyChanged("arrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string arrivalLocationName {
            get {
                return this.arrivalLocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.arrivalLocationNameField, value) != true)) {
                    this.arrivalLocationNameField = value;
                    this.RaisePropertyChanged("arrivalLocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan arrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                if ((this.arrivalTimeField.Equals(value) != true)) {
                    this.arrivalTimeField = value;
                    this.RaisePropertyChanged("arrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime bookingDate {
            get {
                return this.bookingDateField;
            }
            set {
                if ((this.bookingDateField.Equals(value) != true)) {
                    this.bookingDateField = value;
                    this.RaisePropertyChanged("bookingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bookingId {
            get {
                return this.bookingIdField;
            }
            set {
                if ((this.bookingIdField.Equals(value) != true)) {
                    this.bookingIdField = value;
                    this.RaisePropertyChanged("bookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime departureDate {
            get {
                return this.departureDateField;
            }
            set {
                if ((this.departureDateField.Equals(value) != true)) {
                    this.departureDateField = value;
                    this.RaisePropertyChanged("departureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departureLocationName {
            get {
                return this.departureLocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.departureLocationNameField, value) != true)) {
                    this.departureLocationNameField = value;
                    this.RaisePropertyChanged("departureLocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan departureTime {
            get {
                return this.departureTimeField;
            }
            set {
                if ((this.departureTimeField.Equals(value) != true)) {
                    this.departureTimeField = value;
                    this.RaisePropertyChanged("departureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string flightName {
            get {
                return this.flightNameField;
            }
            set {
                if ((object.ReferenceEquals(this.flightNameField, value) != true)) {
                    this.flightNameField = value;
                    this.RaisePropertyChanged("flightName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double flightPrice {
            get {
                return this.flightPriceField;
            }
            set {
                if ((this.flightPriceField.Equals(value) != true)) {
                    this.flightPriceField = value;
                    this.RaisePropertyChanged("flightPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameOnTicket {
            get {
                return this.nameOnTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.nameOnTicketField, value) != true)) {
                    this.nameOnTicketField = value;
                    this.RaisePropertyChanged("nameOnTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int seatId {
            get {
                return this.seatIdField;
            }
            set {
                if ((this.seatIdField.Equals(value) != true)) {
                    this.seatIdField = value;
                    this.RaisePropertyChanged("seatId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableFlightInformation", Namespace="http://schemas.datacontract.org/2004/07/Intel_AirlineReservationService.Serializa" +
        "ble_Models")]
    [System.SerializableAttribute()]
    public partial class AvailableFlightInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime arrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string arrivalLocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan arrivalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime departureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureLocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan departureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string flightNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string flightNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int scheduleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime arrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                if ((this.arrivalDateField.Equals(value) != true)) {
                    this.arrivalDateField = value;
                    this.RaisePropertyChanged("arrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string arrivalLocationName {
            get {
                return this.arrivalLocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.arrivalLocationNameField, value) != true)) {
                    this.arrivalLocationNameField = value;
                    this.RaisePropertyChanged("arrivalLocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan arrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                if ((this.arrivalTimeField.Equals(value) != true)) {
                    this.arrivalTimeField = value;
                    this.RaisePropertyChanged("arrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string classType {
            get {
                return this.classTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.classTypeField, value) != true)) {
                    this.classTypeField = value;
                    this.RaisePropertyChanged("classType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime departureDate {
            get {
                return this.departureDateField;
            }
            set {
                if ((this.departureDateField.Equals(value) != true)) {
                    this.departureDateField = value;
                    this.RaisePropertyChanged("departureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departureLocationName {
            get {
                return this.departureLocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.departureLocationNameField, value) != true)) {
                    this.departureLocationNameField = value;
                    this.RaisePropertyChanged("departureLocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan departureTime {
            get {
                return this.departureTimeField;
            }
            set {
                if ((this.departureTimeField.Equals(value) != true)) {
                    this.departureTimeField = value;
                    this.RaisePropertyChanged("departureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string flightName {
            get {
                return this.flightNameField;
            }
            set {
                if ((object.ReferenceEquals(this.flightNameField, value) != true)) {
                    this.flightNameField = value;
                    this.RaisePropertyChanged("flightName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string flightNumber {
            get {
                return this.flightNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.flightNumberField, value) != true)) {
                    this.flightNumberField = value;
                    this.RaisePropertyChanged("flightNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int scheduleId {
            get {
                return this.scheduleIdField;
            }
            set {
                if ((this.scheduleIdField.Equals(value) != true)) {
                    this.scheduleIdField = value;
                    this.RaisePropertyChanged("scheduleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="flightSchedule", Namespace="http://schemas.datacontract.org/2004/07/Intel_AirlineReservationService.Model")]
    [System.SerializableAttribute()]
    public partial class flightSchedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime arrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int arrivalLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan arrivalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.booking[] bookingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime departureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departureLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan departureTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.flightClassPrice[] flightClassPricesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string flightNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string flightNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.location locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.location location1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int scheduleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.seatingArrangement[] seatingArrangementsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime arrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                if ((this.arrivalDateField.Equals(value) != true)) {
                    this.arrivalDateField = value;
                    this.RaisePropertyChanged("arrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int arrivalLocationId {
            get {
                return this.arrivalLocationIdField;
            }
            set {
                if ((this.arrivalLocationIdField.Equals(value) != true)) {
                    this.arrivalLocationIdField = value;
                    this.RaisePropertyChanged("arrivalLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan arrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                if ((this.arrivalTimeField.Equals(value) != true)) {
                    this.arrivalTimeField = value;
                    this.RaisePropertyChanged("arrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.booking[] bookings {
            get {
                return this.bookingsField;
            }
            set {
                if ((object.ReferenceEquals(this.bookingsField, value) != true)) {
                    this.bookingsField = value;
                    this.RaisePropertyChanged("bookings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime departureDate {
            get {
                return this.departureDateField;
            }
            set {
                if ((this.departureDateField.Equals(value) != true)) {
                    this.departureDateField = value;
                    this.RaisePropertyChanged("departureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departureLocationId {
            get {
                return this.departureLocationIdField;
            }
            set {
                if ((this.departureLocationIdField.Equals(value) != true)) {
                    this.departureLocationIdField = value;
                    this.RaisePropertyChanged("departureLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan departureTime {
            get {
                return this.departureTimeField;
            }
            set {
                if ((this.departureTimeField.Equals(value) != true)) {
                    this.departureTimeField = value;
                    this.RaisePropertyChanged("departureTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.flightClassPrice[] flightClassPrices {
            get {
                return this.flightClassPricesField;
            }
            set {
                if ((object.ReferenceEquals(this.flightClassPricesField, value) != true)) {
                    this.flightClassPricesField = value;
                    this.RaisePropertyChanged("flightClassPrices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string flightName {
            get {
                return this.flightNameField;
            }
            set {
                if ((object.ReferenceEquals(this.flightNameField, value) != true)) {
                    this.flightNameField = value;
                    this.RaisePropertyChanged("flightName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string flightNumber {
            get {
                return this.flightNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.flightNumberField, value) != true)) {
                    this.flightNumberField = value;
                    this.RaisePropertyChanged("flightNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.location location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.location location1 {
            get {
                return this.location1Field;
            }
            set {
                if ((object.ReferenceEquals(this.location1Field, value) != true)) {
                    this.location1Field = value;
                    this.RaisePropertyChanged("location1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int scheduleId {
            get {
                return this.scheduleIdField;
            }
            set {
                if ((this.scheduleIdField.Equals(value) != true)) {
                    this.scheduleIdField = value;
                    this.RaisePropertyChanged("scheduleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.seatingArrangement[] seatingArrangements {
            get {
                return this.seatingArrangementsField;
            }
            set {
                if ((object.ReferenceEquals(this.seatingArrangementsField, value) != true)) {
                    this.seatingArrangementsField = value;
                    this.RaisePropertyChanged("seatingArrangements");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="location", Namespace="http://schemas.datacontract.org/2004/07/Intel_AirlineReservationService.Model")]
    [System.SerializableAttribute()]
    public partial class location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule[] flightSchedulesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule[] flightSchedules1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int locationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule[] flightSchedules {
            get {
                return this.flightSchedulesField;
            }
            set {
                if ((object.ReferenceEquals(this.flightSchedulesField, value) != true)) {
                    this.flightSchedulesField = value;
                    this.RaisePropertyChanged("flightSchedules");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule[] flightSchedules1 {
            get {
                return this.flightSchedules1Field;
            }
            set {
                if ((object.ReferenceEquals(this.flightSchedules1Field, value) != true)) {
                    this.flightSchedules1Field = value;
                    this.RaisePropertyChanged("flightSchedules1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int locationId {
            get {
                return this.locationIdField;
            }
            set {
                if ((this.locationIdField.Equals(value) != true)) {
                    this.locationIdField = value;
                    this.RaisePropertyChanged("locationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.locationNameField, value) != true)) {
                    this.locationNameField = value;
                    this.RaisePropertyChanged("locationName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="booking", Namespace="http://schemas.datacontract.org/2004/07/Intel_AirlineReservationService.Model")]
    [System.SerializableAttribute()]
    public partial class booking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime bookingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bookingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double flightPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule flightScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameOnTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.passenger passengerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int passengerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int scheduleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int seatIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime bookingDate {
            get {
                return this.bookingDateField;
            }
            set {
                if ((this.bookingDateField.Equals(value) != true)) {
                    this.bookingDateField = value;
                    this.RaisePropertyChanged("bookingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bookingId {
            get {
                return this.bookingIdField;
            }
            set {
                if ((this.bookingIdField.Equals(value) != true)) {
                    this.bookingIdField = value;
                    this.RaisePropertyChanged("bookingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double flightPrice {
            get {
                return this.flightPriceField;
            }
            set {
                if ((this.flightPriceField.Equals(value) != true)) {
                    this.flightPriceField = value;
                    this.RaisePropertyChanged("flightPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule flightSchedule {
            get {
                return this.flightScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.flightScheduleField, value) != true)) {
                    this.flightScheduleField = value;
                    this.RaisePropertyChanged("flightSchedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameOnTicket {
            get {
                return this.nameOnTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.nameOnTicketField, value) != true)) {
                    this.nameOnTicketField = value;
                    this.RaisePropertyChanged("nameOnTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.passenger passenger {
            get {
                return this.passengerField;
            }
            set {
                if ((object.ReferenceEquals(this.passengerField, value) != true)) {
                    this.passengerField = value;
                    this.RaisePropertyChanged("passenger");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int passengerId {
            get {
                return this.passengerIdField;
            }
            set {
                if ((this.passengerIdField.Equals(value) != true)) {
                    this.passengerIdField = value;
                    this.RaisePropertyChanged("passengerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int scheduleId {
            get {
                return this.scheduleIdField;
            }
            set {
                if ((this.scheduleIdField.Equals(value) != true)) {
                    this.scheduleIdField = value;
                    this.RaisePropertyChanged("scheduleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int seatId {
            get {
                return this.seatIdField;
            }
            set {
                if ((this.seatIdField.Equals(value) != true)) {
                    this.seatIdField = value;
                    this.RaisePropertyChanged("seatId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="flightClassPrice", Namespace="http://schemas.datacontract.org/2004/07/Intel_AirlineReservationService.Model")]
    [System.SerializableAttribute()]
    public partial class flightClassPrice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule flightScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int scheduleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string classType {
            get {
                return this.classTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.classTypeField, value) != true)) {
                    this.classTypeField = value;
                    this.RaisePropertyChanged("classType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule flightSchedule {
            get {
                return this.flightScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.flightScheduleField, value) != true)) {
                    this.flightScheduleField = value;
                    this.RaisePropertyChanged("flightSchedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int scheduleId {
            get {
                return this.scheduleIdField;
            }
            set {
                if ((this.scheduleIdField.Equals(value) != true)) {
                    this.scheduleIdField = value;
                    this.RaisePropertyChanged("scheduleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="seatingArrangement", Namespace="http://schemas.datacontract.org/2004/07/Intel_AirlineReservationService.Model")]
    [System.SerializableAttribute()]
    public partial class seatingArrangement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string classTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule flightScheduleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int scheduleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool seatAvailabilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int seatIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string classType {
            get {
                return this.classTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.classTypeField, value) != true)) {
                    this.classTypeField = value;
                    this.RaisePropertyChanged("classType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule flightSchedule {
            get {
                return this.flightScheduleField;
            }
            set {
                if ((object.ReferenceEquals(this.flightScheduleField, value) != true)) {
                    this.flightScheduleField = value;
                    this.RaisePropertyChanged("flightSchedule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int scheduleId {
            get {
                return this.scheduleIdField;
            }
            set {
                if ((this.scheduleIdField.Equals(value) != true)) {
                    this.scheduleIdField = value;
                    this.RaisePropertyChanged("scheduleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool seatAvailability {
            get {
                return this.seatAvailabilityField;
            }
            set {
                if ((this.seatAvailabilityField.Equals(value) != true)) {
                    this.seatAvailabilityField = value;
                    this.RaisePropertyChanged("seatAvailability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int seatId {
            get {
                return this.seatIdField;
            }
            set {
                if ((this.seatIdField.Equals(value) != true)) {
                    this.seatIdField = value;
                    this.RaisePropertyChanged("seatId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="passenger", Namespace="http://schemas.datacontract.org/2004/07/Intel_AirlineReservationService.Model")]
    [System.SerializableAttribute()]
    public partial class passenger : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AirlineReservationGUI.Intel_AirlineReservationService.booking[] bookingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int passengerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AirlineReservationGUI.Intel_AirlineReservationService.booking[] bookings {
            get {
                return this.bookingsField;
            }
            set {
                if ((object.ReferenceEquals(this.bookingsField, value) != true)) {
                    this.bookingsField = value;
                    this.RaisePropertyChanged("bookings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                if ((this.dateOfBirthField.Equals(value) != true)) {
                    this.dateOfBirthField = value;
                    this.RaisePropertyChanged("dateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailId {
            get {
                return this.emailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.emailIdField, value) != true)) {
                    this.emailIdField = value;
                    this.RaisePropertyChanged("emailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int passengerId {
            get {
                return this.passengerIdField;
            }
            set {
                if ((this.passengerIdField.Equals(value) != true)) {
                    this.passengerIdField = value;
                    this.RaisePropertyChanged("passengerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Intel_AirlineReservationService.IIntel_AirlineReservationService")]
    public interface IIntel_AirlineReservationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/login", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/loginResponse")]
        int login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/login", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/loginResponse")]
        System.Threading.Tasks.Task<int> loginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/RegisterUser", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/RegisterUserResponse")]
        int RegisterUser(string email, string firstName, string lastName, string password, string dateOfBirth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/RegisterUser", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/RegisterUserResponse")]
        System.Threading.Tasks.Task<int> RegisterUserAsync(string email, string firstName, string lastName, string password, string dateOfBirth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/GetAllLocations", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/GetAllLocationsResponse")]
        string[] GetAllLocations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/GetAllLocations", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/GetAllLocationsResponse")]
        System.Threading.Tasks.Task<string[]> GetAllLocationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/GetBookingHistory", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/GetBookingHistoryResponse")]
        AirlineReservationGUI.Intel_AirlineReservationService.BookingHistory[] GetBookingHistory(int passengerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/GetBookingHistory", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/GetBookingHistoryResponse")]
        System.Threading.Tasks.Task<AirlineReservationGUI.Intel_AirlineReservationService.BookingHistory[]> GetBookingHistoryAsync(int passengerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/GetFlightSchedules", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/GetFlightSchedulesResponse")]
        AirlineReservationGUI.Intel_AirlineReservationService.AvailableFlightInformation[] GetFlightSchedules(int passengerId, string departureLocation, string arrivalLocation, System.DateTime departureDate, string travelClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/GetFlightSchedules", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/GetFlightSchedulesResponse")]
        System.Threading.Tasks.Task<AirlineReservationGUI.Intel_AirlineReservationService.AvailableFlightInformation[]> GetFlightSchedulesAsync(int passengerId, string departureLocation, string arrivalLocation, System.DateTime departureDate, string travelClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/AddFlightSchedule", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/AddFlightScheduleResponse")]
        int AddFlightSchedule(string flightNumber, string flightName, System.DateTime departureDate, System.TimeSpan departureTime, string departureLocation, System.DateTime arrivalDate, System.TimeSpan arrivalTime, string arrivalLocation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/AddFlightSchedule", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/AddFlightScheduleResponse")]
        System.Threading.Tasks.Task<int> AddFlightScheduleAsync(string flightNumber, string flightName, System.DateTime departureDate, System.TimeSpan departureTime, string departureLocation, System.DateTime arrivalDate, System.TimeSpan arrivalTime, string arrivalLocation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/addScheduleClassPrice", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/addScheduleClassPriceResponse" +
            "")]
        void addScheduleClassPrice(int scheduleId, float classPrice1, float classPrice2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/addScheduleClassPrice", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/addScheduleClassPriceResponse" +
            "")]
        System.Threading.Tasks.Task addScheduleClassPriceAsync(int scheduleId, float classPrice1, float classPrice2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/addSeatAvailability", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/addSeatAvailabilityResponse")]
        void addSeatAvailability(int scheduleId, int[] economySeatIds, int[] businessSeatIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/addSeatAvailability", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/addSeatAvailabilityResponse")]
        System.Threading.Tasks.Task addSeatAvailabilityAsync(int scheduleId, int[] economySeatIds, int[] businessSeatIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/GetAvailableSeats", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/GetAvailableSeatsResponse")]
        int[] GetAvailableSeats(int scheduleId, string classType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/GetAvailableSeats", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/GetAvailableSeatsResponse")]
        System.Threading.Tasks.Task<int[]> GetAvailableSeatsAsync(int scheduleId, string classType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/BookSeat", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/BookSeatResponse")]
        int BookSeat(int scheduleId, int seatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/BookSeat", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/BookSeatResponse")]
        System.Threading.Tasks.Task<int> BookSeatAsync(int scheduleId, int seatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/addBooking", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/addBookingResponse")]
        void addBooking(int scheduleId, int passengerId, int seatId, double flightPrice, string nameOnTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/addBooking", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/addBookingResponse")]
        System.Threading.Tasks.Task addBookingAsync(int scheduleId, int passengerId, int seatId, double flightPrice, string nameOnTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/GetAllSchedulesFlights", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/GetAllSchedulesFlightsRespons" +
            "e")]
        AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule[] GetAllSchedulesFlights();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntel_AirlineReservationService/GetAllSchedulesFlights", ReplyAction="http://tempuri.org/IIntel_AirlineReservationService/GetAllSchedulesFlightsRespons" +
            "e")]
        System.Threading.Tasks.Task<AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule[]> GetAllSchedulesFlightsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntel_AirlineReservationServiceChannel : AirlineReservationGUI.Intel_AirlineReservationService.IIntel_AirlineReservationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Intel_AirlineReservationServiceClient : System.ServiceModel.ClientBase<AirlineReservationGUI.Intel_AirlineReservationService.IIntel_AirlineReservationService>, AirlineReservationGUI.Intel_AirlineReservationService.IIntel_AirlineReservationService {
        
        public Intel_AirlineReservationServiceClient() {
        }
        
        public Intel_AirlineReservationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Intel_AirlineReservationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Intel_AirlineReservationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Intel_AirlineReservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int login(string email, string password) {
            return base.Channel.login(email, password);
        }
        
        public System.Threading.Tasks.Task<int> loginAsync(string email, string password) {
            return base.Channel.loginAsync(email, password);
        }
        
        public int RegisterUser(string email, string firstName, string lastName, string password, string dateOfBirth) {
            return base.Channel.RegisterUser(email, firstName, lastName, password, dateOfBirth);
        }
        
        public System.Threading.Tasks.Task<int> RegisterUserAsync(string email, string firstName, string lastName, string password, string dateOfBirth) {
            return base.Channel.RegisterUserAsync(email, firstName, lastName, password, dateOfBirth);
        }
        
        public string[] GetAllLocations() {
            return base.Channel.GetAllLocations();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllLocationsAsync() {
            return base.Channel.GetAllLocationsAsync();
        }
        
        public AirlineReservationGUI.Intel_AirlineReservationService.BookingHistory[] GetBookingHistory(int passengerId) {
            return base.Channel.GetBookingHistory(passengerId);
        }
        
        public System.Threading.Tasks.Task<AirlineReservationGUI.Intel_AirlineReservationService.BookingHistory[]> GetBookingHistoryAsync(int passengerId) {
            return base.Channel.GetBookingHistoryAsync(passengerId);
        }
        
        public AirlineReservationGUI.Intel_AirlineReservationService.AvailableFlightInformation[] GetFlightSchedules(int passengerId, string departureLocation, string arrivalLocation, System.DateTime departureDate, string travelClass) {
            return base.Channel.GetFlightSchedules(passengerId, departureLocation, arrivalLocation, departureDate, travelClass);
        }
        
        public System.Threading.Tasks.Task<AirlineReservationGUI.Intel_AirlineReservationService.AvailableFlightInformation[]> GetFlightSchedulesAsync(int passengerId, string departureLocation, string arrivalLocation, System.DateTime departureDate, string travelClass) {
            return base.Channel.GetFlightSchedulesAsync(passengerId, departureLocation, arrivalLocation, departureDate, travelClass);
        }
        
        public int AddFlightSchedule(string flightNumber, string flightName, System.DateTime departureDate, System.TimeSpan departureTime, string departureLocation, System.DateTime arrivalDate, System.TimeSpan arrivalTime, string arrivalLocation) {
            return base.Channel.AddFlightSchedule(flightNumber, flightName, departureDate, departureTime, departureLocation, arrivalDate, arrivalTime, arrivalLocation);
        }
        
        public System.Threading.Tasks.Task<int> AddFlightScheduleAsync(string flightNumber, string flightName, System.DateTime departureDate, System.TimeSpan departureTime, string departureLocation, System.DateTime arrivalDate, System.TimeSpan arrivalTime, string arrivalLocation) {
            return base.Channel.AddFlightScheduleAsync(flightNumber, flightName, departureDate, departureTime, departureLocation, arrivalDate, arrivalTime, arrivalLocation);
        }
        
        public void addScheduleClassPrice(int scheduleId, float classPrice1, float classPrice2) {
            base.Channel.addScheduleClassPrice(scheduleId, classPrice1, classPrice2);
        }
        
        public System.Threading.Tasks.Task addScheduleClassPriceAsync(int scheduleId, float classPrice1, float classPrice2) {
            return base.Channel.addScheduleClassPriceAsync(scheduleId, classPrice1, classPrice2);
        }
        
        public void addSeatAvailability(int scheduleId, int[] economySeatIds, int[] businessSeatIds) {
            base.Channel.addSeatAvailability(scheduleId, economySeatIds, businessSeatIds);
        }
        
        public System.Threading.Tasks.Task addSeatAvailabilityAsync(int scheduleId, int[] economySeatIds, int[] businessSeatIds) {
            return base.Channel.addSeatAvailabilityAsync(scheduleId, economySeatIds, businessSeatIds);
        }
        
        public int[] GetAvailableSeats(int scheduleId, string classType) {
            return base.Channel.GetAvailableSeats(scheduleId, classType);
        }
        
        public System.Threading.Tasks.Task<int[]> GetAvailableSeatsAsync(int scheduleId, string classType) {
            return base.Channel.GetAvailableSeatsAsync(scheduleId, classType);
        }
        
        public int BookSeat(int scheduleId, int seatId) {
            return base.Channel.BookSeat(scheduleId, seatId);
        }
        
        public System.Threading.Tasks.Task<int> BookSeatAsync(int scheduleId, int seatId) {
            return base.Channel.BookSeatAsync(scheduleId, seatId);
        }
        
        public void addBooking(int scheduleId, int passengerId, int seatId, double flightPrice, string nameOnTicket) {
            base.Channel.addBooking(scheduleId, passengerId, seatId, flightPrice, nameOnTicket);
        }
        
        public System.Threading.Tasks.Task addBookingAsync(int scheduleId, int passengerId, int seatId, double flightPrice, string nameOnTicket) {
            return base.Channel.addBookingAsync(scheduleId, passengerId, seatId, flightPrice, nameOnTicket);
        }
        
        public AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule[] GetAllSchedulesFlights() {
            return base.Channel.GetAllSchedulesFlights();
        }
        
        public System.Threading.Tasks.Task<AirlineReservationGUI.Intel_AirlineReservationService.flightSchedule[]> GetAllSchedulesFlightsAsync() {
            return base.Channel.GetAllSchedulesFlightsAsync();
        }
    }
}
