//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel_AirlineReservationService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int bookingId { get; set; }
        public System.DateTime bookingDate { get; set; }
        public int scheduleId { get; set; }
        public int passengerId { get; set; }
        public int seatId { get; set; }
        public double flightPrice { get; set; }
        public string nameOnTicket { get; set; }
    
        public virtual flightSchedule flightSchedule { get; set; }
        public virtual passenger passenger { get; set; }
    }
}
