//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel_AirlineReservationService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class flightSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public flightSchedule()
        {
            this.bookings = new HashSet<booking>();
            this.flightClassPrices = new HashSet<flightClassPrice>();
            this.seatingArrangements = new HashSet<seatingArrangement>();
        }
    
        public int scheduleId { get; set; }
        public Nullable<System.TimeSpan> departureTime { get; set; }
        public System.DateTime departureDate { get; set; }
        public int departureLocationId { get; set; }
        public Nullable<System.TimeSpan> arrivalTime { get; set; }
        public System.DateTime arrivalDate { get; set; }
        public int arrivalLocationId { get; set; }
        public string flightNumber { get; set; }
        public string flightName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flightClassPrice> flightClassPrices { get; set; }
        public virtual location location { get; set; }
        public virtual location location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seatingArrangement> seatingArrangements { get; set; }
    }
}
