//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intel_AirlineReservationService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class seatingArrangement
    {
        public int scheduleId { get; set; }
        public int seatId { get; set; }
        public string classType { get; set; }
        public bool seatAvailability { get; set; }
    
        public virtual flightSchedule flightSchedule { get; set; }
    }
}
